apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgresql-pv
  namespace: awx
spec:
  storageClassName: awx-postgresql-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /nfs/homelab/awx-volume/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - cf-k8s-master
            - cf-k8s-node1
            - cf-k8s-node2
