apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgresql-pv
  namespace: awx
spec:
  storageClassName: awx-postgresql-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.11
    path: "/volume2/NFS/homelab/awx-volume/postgresql"
